version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]